### PR TITLE
Scribing questions

### PR DESCRIPTION
**Pull request by kxmbrian**
This feature allows teachers to have scribing questions as part of a mission, where students and teachers can draw on a canvas and submit that as an answer. Coursemology/coursemology.org#277

- Teachers may upload PDFs or images as canvas background images. Multipage PDFs are allowed and one question will be produced per page. PDFs are converted and stored as PNG.
- Background images are optional.
- Scribbles by each user may be hidden/show.

Screenshots to come!

### CODE REVIEW

**Comment by kxmbrian** [comment]
screen shot 2015-01-01 at 1 33 44 pm

**Comment by fonglh** [comment]
@raymondtangsc please also ensure that `/usr/bin/pdftoppm` exists on the server. It's in the `poppler-utils` package.

`sudo apt-get install poppler-utils`

**Comment by fonglh** [comment]
@raymondtangsc is there anything else we have to fix? Prof wants this out quite urgently.

**Comment by raymondtangsc** [comment]
please resolve merge conflicts.

**Comment by raymondtangsc** [comment]
Please verify on production.

**Comment by fonglh** [comment]
@raymondtangsc can you install the poppler-utils package and ensure `/usr/bin/pdftoppm` exists on the server? Thanks!

**Comment by raymondtangsc** [comment]
installed. try again.

**Comment by fonglh** [comment]
Thanks! There're some bugfixes we need to make, will submit in separate PRs

**Pull request merged**
